#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

[[ ! $(pidof -x sxhkd) ]] && sxhkd &
~/.config/polybar/launch.sh

#Setup mouse behaviour
~/scripts/tap-to-click.sh
~/scripts/inverse-scroll.sh

#Set keyboard behaviour
setxkbmap -layout gb -option caps:escape

#Set Background
feh --bg-fill $HOME/Pictures/horizon-lake-suwa-1920×1080.png

#Set Power Manager
[[ ! $(pidof -x xfce4-power-manager) ]] && xfce4-power-manager &

#Enable Compton
[[ ! $(pidof -x compton) ]] && compton  &

##STARTUP APPLICATIONS
Firefox 
